### PR TITLE
add (G)ZDoom and Freedoom

### PR DESCRIPTION
**Pull request by darealshinji**
Both packages should be build from the last Git versions:
https://github.com/freedoom/freedoom
https://github.com/coelckers/gzdoom

The package gzdoom-freedoom depends on freedoom-iwads, which is why I did include that package too.
GZDoom will be build with its own fmodex private libs.
If you want to keep those libs in a separate package, you could use the files in https://github.com/darealshinji/Debian/fmodex or https://github.com/darealshinji/Debian/fmodex-private to create such a package.

edit:
Created a ZDoom package from the GZDoom files.

### CODE REVIEW

**Comment by darealshinji** [comment]
Added "You Have to Win the Game". That game is available for free on Steam and the license allows sharing for non-commercial purposes (see copyright file line 47).
Tarball: https://www.sendspace.com/file/9hvrt1

**Comment by ckorn** [comment]
Should the libsteam_api.so really also be published?

**Comment by darealshinji** [comment]
Unfortunately TheGame_NFML requires it.

**Comment by ckorn** [comment]
But is it allowed to be redistributed?

**Comment by darealshinji** [comment]
That's a good question. I'll see if I can find out more about it. I know that simply removing it from TheGame_NFML's ELF header doesn't work, as it still contains its symbols. Maybe we can build a fake libsteam_api.so library which would solve this issue.

**Comment by ckorn** [comment]
The version you can download from their site does not have the steam api:
http://www.piratehearts.com/blog/games/you-have-to-win-the-game/

**Comment by darealshinji** [comment]
Yes, but that's an older version. I'll ask the author if he knows more about libsteam_api.so. Otherwise I'll create a Debian package for that version. I already got Debian files for that version: https://github.com/darealshinji/Debian/tree/master/you-have-to-win-the-game/old-version/debian

PS: Can you add ZDoom too?

**Comment by darealshinji** [comment]
Here's an answer from Mr. Pittman: http://ask.fm/PirateHearts/answer/113768635114
So, if I understand that correctly, redistribution along with the actual software is okay as long as it remains in a binary form.

**Comment by darealshinji** [comment]
Should I change the configuration to use the non-Steam version?

**Comment by ckorn** [comment]
If the non-steam version is as up-to-date.

**Comment by darealshinji** [comment]
Unfortunately not.
Steam version: 1.01.0499
Non-Steam version: 1.01.0405

**Comment by ckorn** [comment]
Is there also an i386 executable? We could make the i386 work on amd64 but not the other way around.

**Comment by darealshinji** [comment]
According to the entry on http://store.steampowered.com/app/286100/ there's only a 64 bit executable. Just mark the package as 'amd64' instead of 'any' in the control file. But the OSX version is 64 bit only too. 32 bit is legacy stuff and belongs to Windows users, imo. ;-)

**Comment by ckorn** [comment]
Well, we currently only can publish packages which build build on i386 at least.

There was never the case that we had an amd64 build without an i386 build.

**Pull request closed without merging**
